data:
  kaggle: "https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce"

spark:
  partition_by: ["order_purchase_week_end_sunday"]
  output_path: output_path
  input_path: brazilian-ecommerce-sample