name: Run Tests and Flake8

on:
  pull_request:
    branches:
      - main

env:
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
  KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run code linter
      run: flake8

    - name: Print KAGGLE_USERNAME
      run: echo "Hello $KAGGLE_USERNAME"

    - name: Run tests
      run: pytest



